# Generated by Django 4.1.4 on 2022-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='body',
            field=models.TextField(),
        ),
    ]
