# Generated by Django 4.1.1 on 2022-12-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_alter_artikel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
