# Generated by Django 4.1.1 on 2022-12-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_resep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='porsi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
