# Generated by Django 4.1.1 on 2022-12-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0008_alter_artikel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
