# Generated by Django 4.1.1 on 2022-12-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0009_artikel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
