# Generated by Django 4.1.1 on 2022-12-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0010_alter_artikel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resep',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='kunci',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='porsi',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='tingkat',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='waktu',
        ),
        migrations.AddField(
            model_name='resep',
            name='idMeal',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strArea',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strCategory',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strDrinkAlternate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient11',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient12',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient13',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient14',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strIngredient9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strInstructions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeal',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMealThumb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure11',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure12',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure13',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure14',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strMeasure9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strTags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='strYoutube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
